<?php

$_lang['pb_field_type_textfield'] = 'Текст';
$_lang['pb_field_type_textarea'] = 'Текстовая область';
$_lang['pb_field_type_richtext'] = 'Текстовый редактор';
$_lang['pb_field_type_texteditor'] = 'ACE';
$_lang['pb_field_type_listbox'] = 'Выпадающий список';
$_lang['pb_field_type_listbox_multiple'] = 'Выпадающий список (мультивыбор)';
$_lang['pb_field_type_resourcelist'] = 'Список ресурсов';
$_lang['pb_field_type_readyblocks'] = 'Готовые блоки';
$_lang['pb_field_type_combo_boolean'] = 'Список Да/Нет';
$_lang['pb_field_type_numberfield'] = 'Числовое поле';
$_lang['pb_field_type_xcheckbox'] = 'Флажок';
$_lang['pb_field_type_checkboxgroup'] = 'Группа флажков';
$_lang['pb_field_type_radiogroup'] = 'Радиокнопка';
$_lang['pb_field_type_file'] = 'Файл';
$_lang['pb_field_type_image'] = 'Изображение';
$_lang['pb_field_type_gallery'] = 'Галерея';
$_lang['pb_field_type_video'] = 'Видео';
$_lang['pb_field_type_button'] = 'Кнопка';
$_lang['pb_field_type_xdatetime'] = 'Дата';
$_lang['pb_field_type_timefield'] = 'Время';
$_lang['pb_field_type_table'] = 'Таблица';
$_lang['pb_field_type_colorpalette'] = 'Цветовая палитра';
$_lang['pb_field_type_readonly'] = 'Только чтение';
$_lang['pb_field_type_hidden'] = 'Скрытое поле';
$_lang['pb_field_type_xtype'] = 'Xtype поле';

$_lang['pb_fields'] = 'Поля';
$_lang['pb_field'] = 'Поле';
$_lang['pb_field_id'] = 'Id';
$_lang['pb_field_caption'] = 'Подпись';
$_lang['pb_field_title'] = 'Заголовок';
$_lang['pb_field_name'] = 'Название';
$_lang['pb_field_name_desc'] = 'Допускаются только латинские буквы в нижнем регистре';
$_lang['pb_field_type'] = 'Тип поля';
$_lang['pb_field_source_path'] = 'Путь к файлам';
$_lang['pb_field_source_path_desc'] = 'Допустимые параметры: [[+resource_id]] и [[+id]]';
$_lang['pb_field_alias'] = 'Алиас';
$_lang['pb_field_width'] = 'Ширина поля';
$_lang['pb_field_width_desc'] = 'От 0 до 100';
$_lang['pb_field_values'] = 'Возможные значения';
$_lang['pb_field_values_desc'] = 'варианты, разделенные ||, например Кошка||Собака или Белый==#ffffff||Черный==#000000';
$_lang['pb_field_xtype'] = 'Xtype поле';
$_lang['pb_field_xtype_desc'] = 'Список полей - https://bobsguides.com/xtype-list.html';
$_lang['pb_field_default'] = 'Значение по умолчанию';
$_lang['pb_field_help'] = 'Описание поля';
$_lang['pb_field_required'] = 'Обязательное поле';
$_lang['pb_field_sort'] = 'Поле для сортировки';
$_lang['pb_field_dir'] = 'Направление сортировки';
$_lang['pb_field_limit'] = 'Лимит';
$_lang['pb_field_processor'] = 'Процессор';
$_lang['pb_field_connector'] = 'URL коннектора';
$_lang['pb_field_time_minvalue'] = 'Мин. время';
$_lang['pb_field_time_maxvalue'] = 'Макс. время';
$_lang['pb_field_time_increment'] = 'Приращение';
$_lang['pb_field_position'] = 'Позиция';
$_lang['pb_field_table'] = 'Таблица';
$_lang['pb_field_where_desc'] = 'Объект JSON с условиями для фильтрации запроса.
Примеры: [{"template:=":"4"}], [{"pagetitle:!=":"Home"}], [{"parent:IN":[34,56]}]';

$_lang['pb_combo_empty'] = 'Нажмите для выбора';